image:
  repository: ghcr.io/caffeinatedtoad/discord-bots
  pullPolicy: Always
  tag: marcus-latest-arm

tts:
  open_router:
    key: ""
  eleven_labs:
    key: ""

marcus:
  audio_dir: "/audio"

resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

securityContext:
  capabilities:
    add:
      - SYS_NICE
      - SYS_RESOURCE
  runAsNonRoot: false

discord:
  token: ""

misc:
  magic_key: ""

pvc_scheduling:
  node_name: ""

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"