apiVersion: apps/v1
kind: Deployment
metadata:
  name: "marcus"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DISCORD_BOT_TOKEN"
              value: "{{- .Values.discord.token }}"
            - name: "magic_key"
              value: "{{- .Values.misc.magic_key }}"
            - name: "OPEN_ROUTER_KEY"
              value: "{{ .Values.tts.open_router.key }}"
            - name: "ELEVEN_LABS_API_KEY"
              value: "{{ .Values.tts.eleven_labs.key }}"
            - name: "MARCUS_AUDIO_DIR"
              value: "{{ .Values.marcus.audio_dir }}"
          volumeMounts:
            - mountPath: "/audio"
              name: marcus-data
            - mountPath: "/memes"
              name: marcus-data
      volumes:
        - name: marcus-data
          persistentVolumeClaim:
            claimName: marcus-data